server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#logging.level.root: DEBUG
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans

spring:
  application:
    name:
      api-gateway

  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
        - id: COMMAND-SERVICE
          uri: lb://COMMAND-SERVICE
          predicates:
            - Path=/api/command/**
        - id: QUERY-SERVICE
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/api/query/**
